[package]
name = "cargo-nocturne"
description = "Cargo subcommand for building, testing, and deploying nocturne contracts."
edition.workspace = true
license.workspace = true
version.workspace = true

[[bin]]
name = "cargo-nocturne"
path = "src/main.rs"

[dependencies]
midnight-zkir = { workspace = true }
midnight-transient-crypto = { workspace = true }
midnight-base-crypto = { workspace = true }
midnight-serialize = { workspace = true }
serde_json = { workspace = true }
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros"] }
anyhow = "1"
