[package]
name = "midnight-primitives"
description = "Low-level utilities for midnight-edsl: field arithmetic, hashing, alignment."
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
midnight-transient-crypto = { workspace = true }
midnight-base-crypto = { workspace = true }
