[package]
name = "midnight-storage"
description = "Ledger storage abstractions for midnight-edsl contracts."
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
midnight-types = { workspace = true }
midnight-base-crypto = { workspace = true }
midnight-transient-crypto = { workspace = true }
